# Site settings
title: Title
email: email@domain.com
description: description goes here
baseurl: "/"
url: "https://thanhminhmr.github.io/"
twitter_username: tname
github_username: gname

# Build settings
markdown: kramdown

theme: jekyll-theme-tactile