# Site settings
title: MrMaThaMi's Blog
email: thanhminh.mr@gmail.com
description: A place to share my experiment.
baseurl: "/"
url: "https://thanhminhmr.github.io/"
twitter_username: tname
github_username: gname

# Build settings
markdown: kramdown

# Theme settings
theme: jekyll-theme-tactile