# Site settings
title:          MrMaThaMi
description:    My diary, mostly about *computary* things…
url:            https://thanhminhmr.github.io

# Author
author:
  name:         Thanh Minh
  url:          https://thanhminhmr.github.io
  email:        thanhminh.mr@gmail.com

# Build settings
markdown:       kramdown

# Theme
remote_theme:   chesterhow/tale

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year/:month/:day/:title
paginate:       10
